### ISSUE TITLE
pergunta geral

### ISSUE THREAD

**Issue by ghost** [GustavoMarks/componente-editor-html#6]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by GustavoMarks** [comment]
Olá! Não está ativo no momento, mas fique a vontade para contribuir, irei avaliar a contribuição.

**Comment by ghost** [comment]
Oi GustavoMarks.

> Olá! Não está ativo no momento, mas fique a vontade para contribuir, irei avaliar a contribuição.

Fico feliz com sua mensagem, é o meu primeiro PR.

**Atualização:** Fiz o fork e vou enviar um pull-request ainda nessa semana. Tenha um ótimo dia e muito obrigado por responder minha dúvida. Como respondeu minha dúvida, vou fechar esse tópico agora.
